# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: html
  # Output file instead of logging results
  output-file: 'linters/sass-lint.html'
# File Options
files:
  include: 'client/assets/**/*.s+(a|c)ss'
# Rule Configuration
rules:
  brace-style:
    style: 1tbs
  class-name-format:
    allow-leading-underscore: false
    convention: hyphenatedlowercase
  extends-before-mixins: 2
  extends-before-declarations: 2
  leading-zero:
    include: false
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 0
  no-important: 2
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  variable-for-property:
    - 2
    -
      properties:
        - margin
        - content
